apiVersion: batch/v1
kind: Job
metadata:
  name: dp-mqtt-h5repack-init-x
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never  # Never | OnFailure

      containers:
      - name: init
        image: localhost:30081/braingeneers/job_h5repack:latest
        imagePullPolicy: Always

        command: ["stdbuf", "-i0", "-o0", "-e0", "/usr/bin/time", "-v", "bash", "-c"]
        args:
          - >-
            python init.py

        resources:
          requests:
            cpu: "1"
            memory: "100Mi"
          limits:
            cpu: "2"
            memory: "1000Mi"

        env:
          - name: "UUID"
            value: "2023-04-17-e-causal_v1"
          - name: "AWS_PROFILE"
            value: "default"
          - name: "TF_CPP_MIN_LOG_LEVEL"
            value: "3"
          - name: "PYTHONUNBUFFERED"
            value: "true"

        volumeMounts:

          # Ceph & SWFS credentials
          - name: "prp-s3-credentials"
            mountPath: "/home/jovyan/.aws/credentials"
            subPath: "credentials"
          - name: "prp-s3-credentials"
            mountPath: "/home/jovyan/.s3cfg"
            subPath: ".s3cfg"

          # kube config
          - name: "kube-config"
            mountPath: "/home/jovyan/.kube"
          # SystemV shared memory
          - name: "dshm"
            mountPath: "/dev/shm"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              # Host blacklist
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - none

      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        - name: kube-config
          secret:
            secretName: kube-config
        # Shared memory (necessary for Python's multiprocessing.shared_memory module to work)
        - name: dshm
          emptyDir:
            medium: Memory
