version: '3'
services:
  # Spike Sorting Listener Service (Sury)
  spike_sorting_listener:
    image: surygeng/spike_sorting_listener:latest
    networks:
      - braingeneers-net

  # Plotly Picroscope Console Service (Pierre)
  plotly_picroscope_console:
    image: plotlydashpicroscopeconsole_picroscope-console
    ports:
      - 8051:8050
    networks:
      - braingeneers-net

  # Strapi Service (Pierre)
  strapi_service:
    image: mystrapi:latest
    ports:
      - 1337:1337
    networks:
      - braingeneers-net

  # Shadows Viewer Service (Pierre)
  shadows_viewer:
    image: shadows_viewer:latest
    ports:
      - 8057:80
    networks:
      - braingeneers-net

  # MQTT Message Broker Service (Pierre / David)
  emqx_message_broker:
    image: emqx/emqx:5.0.4
    ports:
      - 1883:1883
      - 8083-8084:8083-8084
      - 8883:8883
      - 18083:18083
    networks:
      - braingeneers-net

  # Image Viewer Service (Pierre / Victoria)
  image_viewer:
    image: braingeneers/images:latest
    ports:
      - 8058:80
    networks:
      - braingeneers-net

  # Maxwell Dashboard Service (Sury)
  maxwell_dashboard:
    image: surygeng/maxwell_dashboard:latest
    ports:
      - 8060:8050
    networks:
      - braingeneers-net

  # Redis Service (David)
  redis_service:
    image: braingeneers/redis:latest
    ports:
      - 6379:6379
    networks:
      - braingeneers-net

  # Braingeneers Dashboard Service (David)
  braingeneers_dashboard:
    image: braingeneers/dashboard:v1.5
    ports:
      - 8050:8050
    networks:
      - braingeneers-net

  # Picroscope Videostream Service (Pierre)
  picroscope_videostream:
    image: picroscopelivestreamserver_picroscope-videostream
    ports:
      - 700:700
      - 8888:8888
    networks:
      - braingeneers-net

# Network Configuration Common to All Services
networks:
  braingeneers-net:
    driver: bridge
