name: Test

on: [push,pull_request]

env:
  PROJECT_NAME: wetai-mc

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-docker@v1

    - name: Build Docker image
      run: docker build -t wetai-mc .
